export type ReportType = {
  id: string;
  label: string;
  description: string;
  color: string;       // Tailwind color name e.g. 'red'
  bgColor: string;     // e.g. 'bg-red-100'
  textColor: string;   // e.g. 'text-red-700'
  borderColor: string; // e.g. 'border-red-200'
  accentColor: string; // e.g. 'bg-red-500'
  emoji: string;
  imagePrompt: string;
};

export const REPORT_TYPES: ReportType[] = [
  {
    id: 'baches',
    label: 'Baches y Pavimento',
    description: 'Hoyos, grietas o deterioro en calles y banquetas',
    color: 'red',
    bgColor: 'bg-red-50',
    textColor: 'text-red-700',
    borderColor: 'border-red-200',
    accentColor: 'bg-red-500',
    emoji: '🕳️',
    imagePrompt: 'Flat icon of a road with a pothole, municipal services style, clean vector art, orange and red colors',
  },
  {
    id: 'alumbrado',
    label: 'Alumbrado Público',
    description: 'Lámparas apagadas, postes dañados o cables sueltos',
    color: 'amber',
    bgColor: 'bg-amber-50',
    textColor: 'text-amber-700',
    borderColor: 'border-amber-200',
    accentColor: 'bg-amber-500',
    emoji: '💡',
    imagePrompt: 'Flat icon of a street lamp that is broken or dark, municipal services style, clean vector art, amber and yellow colors',
  },
  {
    id: 'agua',
    label: 'Agua y Drenaje',
    description: 'Fugas de agua, drenaje tapado o inundaciones',
    color: 'blue',
    bgColor: 'bg-blue-50',
    textColor: 'text-blue-700',
    borderColor: 'border-blue-200',
    accentColor: 'bg-blue-500',
    emoji: '💧',
    imagePrompt: 'Flat icon of a water pipe with a leak, municipal services style, clean vector art, blue colors',
  },
  {
    id: 'basura',
    label: 'Recolección de Basura',
    description: 'Basura sin recoger, contenedores dañados o tiraderos',
    color: 'green',
    bgColor: 'bg-green-50',
    textColor: 'text-green-700',
    borderColor: 'border-green-200',
    accentColor: 'bg-green-500',
    emoji: '🗑️',
    imagePrompt: 'Flat icon of overflowing trash bins on a street, municipal services style, clean vector art, green colors',
  },
  {
    id: 'parques',
    label: 'Parques y Jardines',
    description: 'Áreas verdes descuidadas, juegos rotos o bancas dañadas',
    color: 'emerald',
    bgColor: 'bg-emerald-50',
    textColor: 'text-emerald-700',
    borderColor: 'border-emerald-200',
    accentColor: 'bg-emerald-500',
    emoji: '🌳',
    imagePrompt: 'Flat icon of a neglected park with overgrown grass, municipal services style, clean vector art, emerald green colors',
  },
  {
    id: 'semaforos',
    label: 'Semáforos y Señales',
    description: 'Semáforos dañados, señales viales faltantes o caídas',
    color: 'orange',
    bgColor: 'bg-orange-50',
    textColor: 'text-orange-700',
    borderColor: 'border-orange-200',
    accentColor: 'bg-orange-500',
    emoji: '🚦',
    imagePrompt: 'Flat icon of a broken traffic light, municipal services style, clean vector art, orange colors',
  },
  {
    id: 'arboles',
    label: 'Árboles Peligrosos',
    description: 'Árboles caídos, ramas peligrosas o raíces dañando banquetas',
    color: 'lime',
    bgColor: 'bg-lime-50',
    textColor: 'text-lime-700',
    borderColor: 'border-lime-200',
    accentColor: 'bg-lime-500',
    emoji: '🌲',
    imagePrompt: 'Flat icon of a fallen dangerous tree on a sidewalk, municipal services style, clean vector art, lime green colors',
  },
  {
    id: 'vandalismo',
    label: 'Vandalismo',
    description: 'Grafiti, daños a propiedad pública o equipamiento urbano',
    color: 'violet',
    bgColor: 'bg-violet-50',
    textColor: 'text-violet-700',
    borderColor: 'border-violet-200',
    accentColor: 'bg-violet-500',
    emoji: '🎨',
    imagePrompt: 'Flat icon of graffiti on a public wall, municipal services style, clean vector art, violet purple colors',
  },
  {
    id: 'seguridad',
    label: 'Seguridad',
    description: 'Situaciones de inseguridad, alumbrado deficiente o zonas de riesgo',
    color: 'pink',
    bgColor: 'bg-pink-50',
    textColor: 'text-pink-700',
    borderColor: 'border-pink-200',
    accentColor: 'bg-pink-500',
    emoji: '🚨',
    imagePrompt: 'Flat icon of a security alert or warning sign in a neighborhood, municipal services style, clean vector art, pink and red colors',
  },
  {
    id: 'animales',
    label: 'Animales',
    description: 'Animales callejeros, fauna dañina o mascotas abandonadas',
    color: 'purple',
    bgColor: 'bg-purple-50',
    textColor: 'text-purple-700',
    borderColor: 'border-purple-200',
    accentColor: 'bg-purple-500',
    emoji: '🐕',
    imagePrompt: 'Flat icon of a stray dog on a street, municipal services style, clean vector art, purple colors',
  },
  {
    id: 'ruido',
    label: 'Ruido Excesivo',
    description: 'Actividades con ruido excesivo que perturban la paz',
    color: 'cyan',
    bgColor: 'bg-cyan-50',
    textColor: 'text-cyan-700',
    borderColor: 'border-cyan-200',
    accentColor: 'bg-cyan-500',
    emoji: '🔊',
    imagePrompt: 'Flat icon of sound waves and noise pollution in a neighborhood, municipal services style, clean vector art, cyan colors',
  },
  {
    id: 'otros',
    label: 'Otros',
    description: 'Cualquier otro problema municipal que necesite atención',
    color: 'slate',
    bgColor: 'bg-slate-50',
    textColor: 'text-slate-700',
    borderColor: 'border-slate-200',
    accentColor: 'bg-slate-500',
    emoji: '📋',
    imagePrompt: 'Flat icon of a municipal services clipboard with checkmarks, clean vector art, slate gray colors',
  },
];

export function getReportType(id: string): ReportType | undefined {
  return REPORT_TYPES.find((t) => t.id === id);
}
